services:
  patient.ms:
    build:
      context: ./patient
      dockerfile: Dockerfile
    container_name: patient.ms
    environment:
      MYSQL_HOST: patient.db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mediscreen
    ports:
      - "8081:8081"
    command:
      - sh -c './wait-for-it.sh patient.db:3306 -s -t 60'
    depends_on:
      - patient.db
    networks:
      - medinet

  patient.db:
    image: mysql:latest
    container_name: patient.db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mediscreen
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - patientdb:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    labels:
      com.github.ricksbrown.one-shot: "true"
    networks:
      - medinet

  note.ms:
    build:
      context: ./note
      dockerfile: Dockerfile
    container_name: note.ms
    environment:
      MONGODB_HOST: note.db
    ports:
      - "8082:8082"
    command:
      - sh -c './wait-for-it.sh note.db:27018 -s -t 60'
    depends_on:
      - note.db
    networks:
      - medinet

  note.db:
    image: mongo:latest
    container_name: note.db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - notedb:/data/db
      - notedbconfig:/data/configdb
      - ./script.js:/docker-entrypoint-initdb.d/script.js:ro
    networks:
      - medinet

  assessment.ms:
    build:
      context: ./assessment
      dockerfile: Dockerfile
    container_name: assessment.ms
    environment:
      PATIENT_HOST: patient.ms
      NOTE_HOST: note.ms
      triggers.url: /app/triggers.txt
    volumes:
      - /Users/hashtuce/Library/Mobile Documents/com~apple~CloudDocs/Projets/Projet 9/triggers.txt:/app/triggers.txt
    ports:
      - "8080:8080"
    depends_on:
      - patient.ms
      - note.ms
    networks:
      - medinet

  front.ms:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front.ms
    environment:
      PATIENT_HOST: patient.ms
      NOTE_HOST: note.ms
      ASSESSMENT_HOST: assessment.ms
    ports:
      - "8083:8083"
    depends_on:
      - patient.ms
      - note.ms
      - assessment.ms
    networks:
      - medinet

volumes:
  notedb:
  notedbconfig:
  patientdb:

networks:
  medinet:

